_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 37
                - 38
                - 53
                - 55
                - 82
            "2":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 53
                - 55
                - 80
                - 82
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.3
            "13": linux-x86_64
auto_scale_lr:
    value:
        base_batch_size: 32
        enable: false
backend_args:
    value: null
data_root:
    value: data/coco/
dataset_type:
    value: CocoDataset
default_hooks:
    value:
        checkpoint:
            interval: 1
            type: CheckpointHook
        early_stopping:
            check_finite: true
            min_delta: 0.001
            monitor: bbox_mAP
            patience: 5
            rule: greater
            stopping_threshold: null
            type: EarlyStoppingHook
        logger:
            interval: 50
            type: LoggerHook
        param_scheduler:
            type: ParamSchedulerHook
        sampler_seed:
            type: DistSamplerSeedHook
        timer:
            type: IterTimerHook
        visualization:
            type: DetVisualizationHook
default_scope:
    value: mmdet
env_cfg:
    value:
        cudnn_benchmark: false
        dist_cfg:
            backend: nccl
        mp_cfg:
            mp_start_method: fork
            opencv_num_threads: 0
lang_model_name:
    value: bert-base-uncased
load_from:
    value: https://download.openmmlab.com/mmdetection/v3.0/grounding_dino/groundingdino_swinb_cogcoor_mmdet-55949c9c.pth
log_level:
    value: INFO
log_processor:
    value:
        by_epoch: true
        type: LogProcessor
        window_size: 50
max_epochs:
    value: 100
model:
    value:
        as_two_stage: true
        backbone:
            attn_drop_rate: 0
            convert_weights: false
            depths:
                - 2
                - 2
                - 18
                - 2
            drop_path_rate: 0.3
            drop_rate: 0
            embed_dims: 128
            mlp_ratio: 4
            num_heads:
                - 4
                - 8
                - 16
                - 32
            out_indices:
                - 1
                - 2
                - 3
            patch_norm: true
            pretrain_img_size: 384
            qk_scale: null
            qkv_bias: true
            type: SwinTransformer
            window_size: 12
            with_cp: true
        bbox_head:
            contrastive_cfg:
                bias: false
                log_scale: 0
                max_text_len: 256
            loss_bbox:
                loss_weight: 5
                type: L1Loss
            loss_cls:
                alpha: 0.25
                gamma: 2
                loss_weight: 1
                type: FocalLoss
                use_sigmoid: true
            loss_iou:
                loss_weight: 2
                type: GIoULoss
            num_classes: 80
            sync_cls_avg_factor: true
            type: GroundingDINOHead
        data_preprocessor:
            bgr_to_rgb: true
            mean:
                - 123.675
                - 116.28
                - 103.53
            pad_mask: false
            std:
                - 58.395
                - 57.12
                - 57.375
            type: DetDataPreprocessor
        decoder:
            layer_cfg:
                cross_attn_cfg:
                    dropout: 0
                    embed_dims: 256
                    num_heads: 8
                cross_attn_text_cfg:
                    dropout: 0
                    embed_dims: 256
                    num_heads: 8
                ffn_cfg:
                    embed_dims: 256
                    feedforward_channels: 2048
                    ffn_drop: 0
                self_attn_cfg:
                    dropout: 0
                    embed_dims: 256
                    num_heads: 8
            num_layers: 6
            post_norm_cfg: null
            return_intermediate: true
        dn_cfg:
            box_noise_scale: 1
            group_cfg:
                dynamic: true
                num_dn_queries: 100
                num_groups: null
            label_noise_scale: 0.5
        encoder:
            fusion_layer_cfg:
                embed_dim: 1024
                init_values: 0.0001
                l_dim: 256
                num_heads: 4
                v_dim: 256
            layer_cfg:
                ffn_cfg:
                    embed_dims: 256
                    feedforward_channels: 2048
                    ffn_drop: 0
                self_attn_cfg:
                    dropout: 0
                    embed_dims: 256
                    num_levels: 4
            num_cp: 6
            num_layers: 6
            text_layer_cfg:
                ffn_cfg:
                    embed_dims: 256
                    feedforward_channels: 1024
                    ffn_drop: 0
                self_attn_cfg:
                    dropout: 0
                    embed_dims: 256
                    num_heads: 4
        language_model:
            add_pooling_layer: false
            name: bert-base-uncased
            pad_to_max: false
            special_tokens_list:
                - '[CLS]'
                - '[SEP]'
                - .
                - '?'
            type: BertModel
            use_sub_sentence_represent: true
        neck:
            act_cfg: null
            bias: true
            in_channels:
                - 256
                - 512
                - 1024
            kernel_size: 1
            norm_cfg:
                num_groups: 32
                type: GN
            num_outs: 4
            out_channels: 256
            type: ChannelMapper
        num_queries: 900
        positional_encoding:
            normalize: true
            num_feats: 128
            offset: 0
            temperature: 20
        test_cfg:
            max_per_img: 300
        train_cfg:
            assigner:
                match_costs:
                    - type: BinaryFocalLossCost
                      weight: 2
                    - box_format: xywh
                      type: BBoxL1Cost
                      weight: 5
                    - iou_mode: giou
                      type: IoUCost
                      weight: 2
                type: HungarianAssigner
        type: GroundingDINO
        with_box_refine: true
optim_wrapper:
    value:
        clip_grad:
            max_norm: 0.1
            norm_type: 2
        optimizer:
            lr: 0.0001
            type: AdamW
            weight_decay: 0.0001
        paramwise_cfg:
            custom_keys:
                absolute_pos_embed:
                    decay_mult: 0
                backbone:
                    lr_mult: 0.1
        type: OptimWrapper
param_scheduler:
    value:
        - begin: 0
          by_epoch: true
          end: 100
          gamma: 0.1
          milestones:
            - 11
          type: MultiStepLR
resume:
    value: false
test_cfg:
    value:
        type: TestLoop
test_dataloader:
    value:
        batch_size: 1
        dataset:
            ann_file: annotations/instances_val2017.json
            backend_args: null
            data_prefix:
                img: val2017/
            data_root: data/coco/
            pipeline:
                - backend_args: null
                  type: LoadImageFromFile
                - keep_ratio: true
                  scale:
                    - 800
                    - 1333
                  type: FixScaleResize
                - type: LoadAnnotations
                  with_bbox: true
                - meta_keys:
                    - img_id
                    - img_path
                    - ori_shape
                    - img_shape
                    - scale_factor
                    - text
                    - custom_entities
                  type: PackDetInputs
            return_classes: true
            test_mode: true
            type: CocoDataset
        drop_last: false
        num_workers: 2
        persistent_workers: true
        sampler:
            shuffle: false
            type: DefaultSampler
test_evaluator:
    value:
        ann_file: data/coco/annotations/instances_val2017.json
        backend_args: null
        format_only: false
        metric: bbox
        type: CocoMetric
test_pipeline:
    value:
        - backend_args: null
          type: LoadImageFromFile
        - keep_ratio: true
          scale:
            - 800
            - 1333
          type: FixScaleResize
        - type: LoadAnnotations
          with_bbox: true
        - meta_keys:
            - img_id
            - img_path
            - ori_shape
            - img_shape
            - scale_factor
            - text
            - custom_entities
          type: PackDetInputs
train_cfg:
    value:
        max_epochs: 12
        type: EpochBasedTrainLoop
        val_interval: 1
train_dataloader:
    value:
        batch_sampler:
            type: AspectRatioBatchSampler
        batch_size: 2
        dataset:
            ann_file: annotations/instances_train2017.json
            backend_args: null
            data_prefix:
                img: train2017/
            data_root: data/coco/
            filter_cfg:
                filter_empty_gt: false
                min_size: 32
            pipeline:
                - backend_args: null
                  type: LoadImageFromFile
                - type: LoadAnnotations
                  with_bbox: true
                - prob: 0.5
                  type: RandomFlip
                - transforms:
                    - - keep_ratio: true
                        scales:
                            - - 480
                              - 1333
                            - - 512
                              - 1333
                            - - 544
                              - 1333
                            - - 576
                              - 1333
                            - - 608
                              - 1333
                            - - 640
                              - 1333
                            - - 672
                              - 1333
                            - - 704
                              - 1333
                            - - 736
                              - 1333
                            - - 768
                              - 1333
                            - - 800
                              - 1333
                        type: RandomChoiceResize
                    - - keep_ratio: true
                        scales:
                            - - 400
                              - 4200
                            - - 500
                              - 4200
                            - - 600
                              - 4200
                        type: RandomChoiceResize
                      - allow_negative_crop: true
                        crop_size:
                            - 384
                            - 600
                        crop_type: absolute_range
                        type: RandomCrop
                      - keep_ratio: true
                        scales:
                            - - 480
                              - 1333
                            - - 512
                              - 1333
                            - - 544
                              - 1333
                            - - 576
                              - 1333
                            - - 608
                              - 1333
                            - - 640
                              - 1333
                            - - 672
                              - 1333
                            - - 704
                              - 1333
                            - - 736
                              - 1333
                            - - 768
                              - 1333
                            - - 800
                              - 1333
                        type: RandomChoiceResize
                  type: RandomChoice
                - meta_keys:
                    - img_id
                    - img_path
                    - ori_shape
                    - img_shape
                    - scale_factor
                    - flip
                    - flip_direction
                    - text
                    - custom_entities
                  type: PackDetInputs
            return_classes: true
            type: CocoDataset
        num_workers: 2
        persistent_workers: true
        sampler:
            shuffle: true
            type: DefaultSampler
train_pipeline:
    value:
        - backend_args: null
          type: LoadImageFromFile
        - type: LoadAnnotations
          with_bbox: true
        - prob: 0.5
          type: RandomFlip
        - transforms:
            - - keep_ratio: true
                scales:
                    - - 480
                      - 1333
                    - - 512
                      - 1333
                    - - 544
                      - 1333
                    - - 576
                      - 1333
                    - - 608
                      - 1333
                    - - 640
                      - 1333
                    - - 672
                      - 1333
                    - - 704
                      - 1333
                    - - 736
                      - 1333
                    - - 768
                      - 1333
                    - - 800
                      - 1333
                type: RandomChoiceResize
            - - keep_ratio: true
                scales:
                    - - 400
                      - 4200
                    - - 500
                      - 4200
                    - - 600
                      - 4200
                type: RandomChoiceResize
              - allow_negative_crop: true
                crop_size:
                    - 384
                    - 600
                crop_type: absolute_range
                type: RandomCrop
              - keep_ratio: true
                scales:
                    - - 480
                      - 1333
                    - - 512
                      - 1333
                    - - 544
                      - 1333
                    - - 576
                      - 1333
                    - - 608
                      - 1333
                    - - 640
                      - 1333
                    - - 672
                      - 1333
                    - - 704
                      - 1333
                    - - 736
                      - 1333
                    - - 768
                      - 1333
                    - - 800
                      - 1333
                type: RandomChoiceResize
          type: RandomChoice
        - meta_keys:
            - img_id
            - img_path
            - ori_shape
            - img_shape
            - scale_factor
            - flip
            - flip_direction
            - text
            - custom_entities
          type: PackDetInputs
val_cfg:
    value:
        type: ValLoop
val_dataloader:
    value:
        batch_size: 1
        dataset:
            ann_file: annotations/instances_val2017.json
            backend_args: null
            data_prefix:
                img: val2017/
            data_root: data/coco/
            pipeline:
                - backend_args: null
                  type: LoadImageFromFile
                - keep_ratio: true
                  scale:
                    - 800
                    - 1333
                  type: FixScaleResize
                - type: LoadAnnotations
                  with_bbox: true
                - meta_keys:
                    - img_id
                    - img_path
                    - ori_shape
                    - img_shape
                    - scale_factor
                    - text
                    - custom_entities
                  type: PackDetInputs
            return_classes: true
            test_mode: true
            type: CocoDataset
        drop_last: false
        num_workers: 2
        persistent_workers: true
        sampler:
            shuffle: false
            type: DefaultSampler
val_evaluator:
    value:
        ann_file: data/coco/annotations/instances_val2017.json
        backend_args: null
        format_only: false
        metric: bbox
        type: CocoMetric
vis_backends:
    value:
        - type: LocalVisBackend
visualizer:
    value:
        name: visualizer
        type: DetLocalVisualizer
        vis_backends:
            - type: LocalVisBackend
work_dir:
    value: ./work_dirs/co_dino_custom
